"""link messages to plans

Revision ID: d1354dd22a7d
Revises: ae4e01685453
Create Date: 2026-09-26 12:09:24.417813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1354dd22a7d'
down_revision: Union[str, None] = 'ae4e01685453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('plan_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('messages_plan_id_fkey', 'messages', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_plan_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'plan_id')
    # ### end Alembic commands ###
