import { useMemo } from "react";
import { FolderCode } from "lucide-react";
import type { Plan } from "../../api/plans";
import type { Project } from "../../api/projects";
import DemoBadge from "../../components/DemoBadge";
import PanelEmptyState from "../../components/PanelEmptyState";
import { useAgentWorkspace } from "../agents/agentStore";
import BuiltCodeActions from "./BuiltCodeActions";
import CodeBrowser from "./CodeBrowser";
import { projectFiles } from "./projectFiles";
import type { BuildProgress } from "./useBuildProgress";

type CodeViewProps = {
  project: Project;
  /** The approved plan the app was built from. */
  plan: Plan | null;
  progress: BuildProgress | null;
};

/** Code for projects Architect built: example-app source plus files generated from the plan. */
export default function CodeView({ project, plan, progress }: CodeViewProps) {
  // Agent edits and the framework choice from the Agents tab show up in the agent files.
  const { workspace } = useAgentWorkspace(project.id, plan ? { id: plan.id, agents: plan.content.agents } : null);
  const build = progress?.build;

  const allFiles = useMemo(() => {
    if (!plan || !build) return [];
    const overrides = workspace && {
      framework: workspace.framework,
      agents: workspace.agents.map((agent) => ({
        name: agent.name,
        role: agent.role,
        tools: agent.tools.filter((tool) => tool.enabled).map((tool) => tool.name),
      })),
    };
    return projectFiles(project.name, plan.content, build, overrides ?? undefined);
  }, [project.name, plan, build, workspace]);

  if (!plan || !progress) {
    return (
      <PanelEmptyState
        icon={FolderCode}
        title="No files yet"
        body="Architect writes the code when it builds your app. Approve the plan in the chat to start the build."
      />
    );
  }

  // While building, files appear as the step that creates them finishes.
  const doneSteps = new Set(progress.build.steps.filter((_, i) => progress.stepStates[i] === "done").map((s) => s.id));
  const files = progress.finished ? allFiles : allFiles.filter((file) => doneSteps.has(file.stepId));
  const lastDone = progress.currentIndex > 0 ? progress.build.steps[progress.currentIndex - 1]?.id : undefined;
  const freshSteps = new Set(!progress.finished && lastDone ? [lastDone] : []);

  if (files.length === 0) {
    return (
      <PanelEmptyState icon={FolderCode} title="Writing the first files" body="Files appear here as each build step finishes." />
    );
  }

  return (
    <CodeBrowser
      files={files}
      freshSteps={freshSteps}
      preferredPath="frontend/src/App.tsx"
      footer="Generated by Architect. To change something, describe it in the chat."
      toolbar={
        progress.finished ? (
          <BuiltCodeActions project={project} build={progress.build} files={files} />
        ) : (
          <span className="text-[11px] text-muted">Download and GitHub sync are available once the build finishes.</span>
        )
      }
      header={
        <span className="flex items-center justify-between gap-2">
          {files.length} files{progress.finished ? "" : " so far"}
          <DemoBadge
            label="Example code"
            explanation="In this prototype, the frontend files come from a ready-made example app, and the backend and agent files are generated from your plan. They show what the code would look like; they aren't the code behind the preview."
          />
        </span>
      }
    />
  );
}
