import { useEffect, useMemo, useState } from "react";
import { Check, Copy, Lock } from "lucide-react";
import { highlightLines, languageFor, type TokenKind } from "../../lib/highlight";
import type { ProjectFile } from "./projectFiles";

const tokenClass: Record<TokenKind, string> = {
  plain: "",
  comment: "text-muted italic",
  string: "text-success",
  number: "text-danger",
  keyword: "text-accent font-medium",
  tag: "text-accent",
  heading: "font-semibold",
};

type LoadState = { path: string; content: string } | { path: string; error: string };

export default function CodeViewer({ file }: { file: ProjectFile }) {
  const [loaded, setLoaded] = useState<LoadState | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let cancelled = false;
    file
      .load()
      .then((content) => !cancelled && setLoaded({ path: file.path, content }))
      .catch(() => !cancelled && setLoaded({ path: file.path, error: "This file couldn't be opened. Try selecting it again." }));
    return () => {
      cancelled = true;
    };
  }, [file]);

  const current = loaded?.path === file.path ? loaded : null;
  const content = current && "content" in current ? current.content : null;
  const lines = useMemo(() => (content === null ? [] : highlightLines(content, languageFor(file.path))), [content, file.path]);

  async function copy() {
    if (content === null) return;
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard can be blocked by the browser; the code is still selectable by hand.
    }
  }

  return (
    <div className="flex h-full min-w-0 flex-col">
      <div className="flex h-9 shrink-0 items-center gap-2 border-b border-line px-3">
        <span className="truncate font-mono text-xs">{file.path}</span>
        <span className="flex shrink-0 items-center gap-1 rounded bg-surface px-1.5 py-0.5 text-[10px] text-muted">
          <Lock className="h-3 w-3" aria-hidden />
          Read-only
        </span>
        <button
          type="button"
          onClick={copy}
          disabled={content === null}
          className="ml-auto flex shrink-0 items-center gap-1 rounded px-1.5 py-1 text-[11px] text-muted hover:bg-surface hover:text-ink"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-success" aria-hidden /> : <Copy className="h-3.5 w-3.5" aria-hidden />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <div className="min-h-0 flex-1 overflow-auto">
        {current === null && <p className="p-4 text-xs text-muted">Opening {file.path.split("/").pop()}</p>}
        {current && "error" in current && <p className="p-4 text-xs text-danger">{current.error}</p>}
        {content !== null && (
          <pre className="py-2 font-mono text-xs leading-5">
            {lines.map((tokens, index) => (
              <div key={index} className="flex hover:bg-surface/60">
                <span className="w-10 shrink-0 select-none pr-3 text-right text-muted/60">{index + 1}</span>
                <code className="whitespace-pre pr-4">
                  {tokens.map((token, i) => (
                    <span key={i} className={tokenClass[token.kind]}>
                      {token.text}
                    </span>
                  ))}
                </code>
              </div>
            ))}
          </pre>
        )}
      </div>
      <p className="shrink-0 border-t border-line px-3 py-1.5 text-[11px] text-muted">
        Generated by Architect. To change something, describe it in the chat.
      </p>
    </div>
  );
}
