/** Backend and project files "generated" from the approved plan, for the read-only Code tab. */
import type { PlanAgent, PlanContent } from "../api/plans";

export function slug(text: string, separator = "-"): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, separator)
      .replace(new RegExp(`^\\${separator}+|\\${separator}+$`, "g"), "") || "app"
  );
}

export function componentName(text: string): string {
  return text
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join("");
}

export function readme(projectName: string, plan: PlanContent): string {
  return `# ${projectName}

${plan.summary}

## Agents

${plan.agents.map((agent) => `- **${agent.name}**: ${agent.role}`).join("\n")}

## Pages

${plan.pages.map((page) => `- **${page.name}**: ${page.purpose}`).join("\n")}

## Integrations

${plan.integrations.length ? plan.integrations.map((name) => `- ${name}`).join("\n") : "None"}

## Running locally

\`\`\`
cd backend && uvicorn app.main:app --reload
cd frontend && npm run dev
\`\`\`

Generated by Architect.
`;
}

export function packageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: slug(projectName),
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: { dev: "vite", build: "tsc -b && vite build", test: "vitest run" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1", "lucide-react": "^0.460.0" },
      devDependencies: { typescript: "~5.6.2", vite: "^6.0.0", tailwindcss: "^3.4.15", vitest: "^2.1.0" },
    },
    null,
    2,
  );
}

export function mainPy(projectName: string, plan: PlanContent): string {
  const routers = plan.pages.map((page) => slug(page.name, "_"));
  return `"""${projectName} API. Generated by Architect."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers import ${routers.join(", ")}

app = FastAPI(title="${projectName}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://${slug(projectName).slice(0, 40)}.architect.app"],
    allow_methods=["*"],
    allow_headers=["*"],
)

${routers.map((router) => `app.include_router(${router}.router)`).join("\n")}


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}
`;
}

export function agentPy(agent: PlanAgent): string {
  const tools = agent.tools.map((tool) => slug(tool, "_"));
  const className = componentName(agent.name) || "Agent";
  return `"""${agent.name}: ${agent.role}"""

from architect.agents import Agent, tool

SYSTEM_PROMPT = """
You are the ${agent.name}.
${agent.role}
If you are not sure, hand the task to a person instead of guessing.
"""

${tools
  .map(
    (name, index) => `
@tool(description="${agent.tools[index]}")
async def ${name}(context: dict) -> dict:
    return await context["services"].call("${name}", context["input"])
`,
  )
  .join("")}

${className} = Agent(
    name="${slug(agent.name, "_")}",
    system_prompt=SYSTEM_PROMPT,
    tools=[${tools.join(", ")}],
    model="default",
    handoff_to_human=True,
)
`;
}

export function integrationPy(name: string): string {
  const id = slug(name, "_");
  return `"""Connector for ${name}. Credentials are read from the environment, never stored in code."""

import os

from architect.integrations import Connector

${id} = Connector(
    name="${id}",
    display_name="${name}",
    credentials_env="${id.toUpperCase()}_TOKEN",
    token=os.environ.get("${id.toUpperCase()}_TOKEN"),
)
`;
}

export function testsPy(plan: PlanContent): string {
  return `"""Smoke tests generated with the app."""

from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health() -> None:
    assert client.get("/health").json() == {"status": "ok"}
${plan.pages
  .map(
    (page) => `

def test_${slug(page.name, "_")}_page_loads() -> None:
    assert client.get("/api/${slug(page.name)}").status_code == 200`,
  )
  .join("")}
`;
}

export function architectJson(projectName: string, plan: PlanContent): string {
  return JSON.stringify(
    {
      name: projectName,
      template: plan.template_key,
      agents: plan.agents.map((agent) => ({ id: slug(agent.name, "_"), tools: agent.tools.map((tool) => slug(tool, "_")) })),
      pages: plan.pages.map((page) => `/${slug(page.name)}`),
      integrations: plan.integrations.map((name) => slug(name, "_")),
    },
    null,
    2,
  );
}
